#!/system/bin/sh

# Due to unknown bugs of Android usb config, we need to trigger it
# manually at start-up. It doesn't hurt anyway.
# Use USB mass storage instead of MTP by default.
setprop sys.usb.config `getprop sys.usb.config`
